rustup target add aarch64-unknown-linux-gnu
rustup target add i686-pc-windows-gnu
rustup target add i686-pc-windows-msvc
rustup target add i686-unknown-linux-gnu
rustup target add x86_64-apple-darwin
rustup target add x86_64-pc-windows-gnu
rustup target add x86_64-pc-windows-msvc
rustup target add x86_64-unknown-linux-gnu
cargo build --target=aarch64-unknown-linux-gnu --release
cargo build --target=i686-pc-windows-gnu --release
cargo build --target=i686-pc-windows-msvc --release
cargo build --target=i686-unknown-linux-gnu --release
cargo build --target=x86_64-apple-darwin --release
cargo build --target=x86_64-pc-windows-gnu --release
cargo build --target=x86_64-pc-windows-msvc --release
cargo build --target=x86_64-unknown-linux-gnu --release
